services:
  - type: web
    name: safeguard-ai-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://familysafe-ai.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: safeguard-ai-data
      mountPath: /data
      sizeGB: 1
